# pylint: skip-file

from pixwin.types import Blue, Green, Pixel, Red


def get_rgb(device_context_handle: int, x: int, y: int) -> Pixel: ...

def get_red_value(device_context_handle: int, x: int, y: int) -> Red: ...

def get_blue_value(device_context_handle: int, x: int, y: int) -> Blue: ...

def get_green_value(device_context_handle: int, x: int, y: int) -> Green: ...
