name: Build

on:
  push:
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - pixwin/**

jobs:
  python:
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11, 3.12]

    uses: winstxnhdw/actions/.github/workflows/python.yml@main
    with:
      runs-on: windows-latest
      python-version: ${{ matrix.python-version }}
      disable-test: true

  install:
    runs-on: windows-latest

    steps:
      - name: Install PixWin
        run: pip install git+https://github.com/winstxnhdw/PixWin

      - name: Mini smoke test
        run: python -c "from pixwin import PixWin; PixWin().__enter__().get_pixel(0, 0)"


