name: Build

on:
  push:
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - setup.py
      - '**.py'

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install the development dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: pylint --recursive=y .

  type-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install the development dependencies
        run: pip install -r requirements.txt

      - name: Type Check
        run: pyright

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build the extension
        run: python setup.py build_ext --inplace

  test:
    runs-on: windows-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install PixWin
        run: pip install git+https://github.com/winstxnhdw/PixWin

      - name: Mini smoke test
        run: python -c "from pixwin import PixWin; PixWin().__enter__().get_pixel(0, 0)"
